name: Attendit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.9.0-0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  koukicons: ^2.0.3
  
  #auth
  device_info: ^0.4.2+4
  # UI
  pagination_view: ^1.0.3+2
  cached_network_image: ^2.2.0+1
  gradient_app_bar: ^0.1.3
  percent_indicator: ^2.1.5
  persistent_bottom_nav_bar: ^2.0.5
  bubble_tab_indicator: ^0.1.4
  auto_size_text: ^2.1.0
  simple_animations: ^2.2.1
  solid_bottom_sheet: ^0.1.9
  flutter_swiper: ^1.1.6
  url_launcher: ^5.5.0
  file_picker: ^1.13.3
  avatar_glow: ^1.2.0
  flutter_svg: ^0.18.0
  photo_view: ^0.9.2
  qr_flutter: ^3.2.0
  pull_to_refresh: ^1.6.1

  # Notifications
  firebase_messaging: ^6.0.16
  
  # outline icon
  outline_material_icons: ^0.1.1

  # Network
  graphql_flutter: ^3.1.0
  data_connection_checker: ^0.3.4
  http: ^0.12.2

  # Dart data class
  json_serializable: ^3.4.0
  freezed_annotation: ^0.11.0+1

  # Dependency Injection
  get_it: ^4.0.4
  injectable: ^1.0.4

  # State management
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3

  # Caching
  hive: ^1.4.3

  # Misc
  dartz: ^0.9.1
  rxdart: ^0.24.1
  path_provider: ^1.6.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  freezed: ^0.11.5
  injectable_generator: ^1.0.4
  build_runner: ^1.10.0

  # Linting
  effective_dart: ^1.2.4

  # Testing
  bloc_test: ^7.0.0
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  #  assets:
  #    - assets/Assignment/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Karala
      fonts:
        - asset: assets/fonts/Karla/Karla-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
